### PR TITLE
Feat: MeowerBot.py 3.0 Rewrite

### PR DESCRIPTION
**Pull request by showierdata9978**
Fully Breaking Changes

- `https://webhooks.meower.org/webhook/<id:str>/<token:str>/<chat_id>/post `
	```js
	{
		"name": str // username,
		"message": str // the post you want to send
	}
- Remove All other routes

New Features:

- Returns Post
- You can get the profile picture via `https://webhooks.meower.org/profile/<id:str>`
	```js
	 {
	    "error": False,
        "pfp": str,
        "chat_id": str,
        "perms":  int
      }

- Alot more secure
	- Everything related to creating webhooks and moderating is done through the bot
	   This means its easier to stop impersinators
	- You can no longer easily post in home.
	- You can no longer easily post in livechat
	- Both of those points are locked to MANAGE_CHATS

### CODE REVIEW

**Comment by WlodekM** [comment]
what is <id:str> and <token:str>

**Comment by showierdata9978** [comment]
> what is <id:str> and <token:str>

url parameters

**Comment by WlodekM** [comment]
yeah but what do i set them to?

**Comment by showierdata9978** [comment]
> yeah but what do i set them to?

its the url you get from `@Webhooks mod create {chat id} {pfp}`

**Pull request merged**
